Repository rahulkhandait-sde/cineverse, pull requests merged in 2025-08, with the labels that each got.

#24 feat: Add Dockerfile and .dockerignore for containerization
  .dockerignore
  Dockerfile
Labels: gssoc25, level1

#16 feat: Add search history functionality
  src/components/SearchBar.tsx
Labels: gssoc25, level1

#38 added the footer for copyright
  package-lock.json
  package.json
  src/components/LoadingStates.tsx
Labels: gssoc25, level1

#33 Add Watchlist
  src/app/watchlist/page.tsx
  src/components/Header.tsx
  src/components/MovieCard.tsx
  src/components/WatchlistButton.tsx
  src/store/store.ts
  src/store/watchlistSlice.ts
Labels: gssoc25, level2

#61 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: gssoc25, level1

#55 Added User Authentication System
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/App.js
  src/app/login/login.css
  src/app/login/page.js
  src/app/signup/page.js
  src/app/signup/signup.css
  src/components/Header.tsx
Labels: gssoc25, level3
